= API Management with Kong 
:toc:

== Install Kong (and PostgreSQL dependency)

https://docs.konghq.com/install/docker
	

Kong 5 min quickstart 

https://docs.konghq.com/1.3.x/getting-started/quickstart/

== Konga 

Konga is a non-official GUI for kong administration (official Kong Admin GUI is available only for Kong enterprise) 

	git clone https://github.com/pantsel/konga.git
	cd konga
	npm i
	npm start
	http://localhost:1337 

== Adding services and routes to Kong

*Service* is the name Kong uses to refer to the upstream APIs and microservices it manages. +

	curl -i -X POST --url http://localhost:8001/services/ --data 'name=customer' --data 'url=http://docker.for.mac.localhost:8080'

IMPORTANT: Kong is running in a docker container using `--network=kong-net` when calling services on same machine remember to replace `http://localhost` by `http://docker.for.mac.localhost`

*Routes* specify how (and if) requests are sent to their services after they reach Kong.

	curl -i -X POST --url http://localhost:8001/services/customer/routes --data 'paths[]=/v2/customers'

and action... 
  
IMPORTANT: Customer service must be up and running...
  
	curl -s http://localhost:8000/v2/customers/29bf7bc3-eb4e-432a-b192-1cdc3805ddab	| pjson
	